version: "3.7"

services:
  app:
    #image: contrerasadr/devops-training-python-app:0.0.1
    build: 
      context: .
      dockerfile: devops/Dockerfile
    container_name: my-flask-app-dc
    restart: unless-stopped
    networks:
      - devops_training_net #scalian_training
    environment:
      DB_USER: root
      DB_PWD: rootpwd
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: knights
    depends_on:
      - db
    ports:
      - "5001:5000"

  
  db:
    image: postgres:16-alpine
    container_name: my-flask-app-db
    restart: always
    ports:
      - "32000:5432"
    environment:
      POSTGRES_PASSWORD: rootpwd
      POSTGRES_USER: root
      POSTGRES_DB: knights
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
    networks:
      devops_training_net:#scalian_training:

networks:
  devops_training_net:#scalian_training:
    driver: bridge
    external: true
  
volumes:

  dbdata:

